name: Build FNF Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install haxelib
        run: |
          haxelib setup C:\haxelib
          haxelib install hmm
          haxelib run hmm install

      - name: Install dependencies
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install hxcpp
          haxelib install hscript
          haxelib install hxjson

      - name: Setup Lime
        run: haxelib run lime setup

      - name: Build for Windows
        run: haxelib run lime build windows
